[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "python3 -m venv .venv",
  ".venv/bin/pip install gl-client requests",
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
